### ISSUE TITLE
LinA

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/streaming-instability#1]
### Tasks
- Answers in Eq. 10 in YJ07
- CC's probgen & input come from Eqs. 1-4
- [ ] __Growth rates__: semilog plot of max. density vs. $t$
    - [x] Difference of max. density w/ initial (not absolute)
    - [x] Plot minimum density as well (should be symmetrical)
    - [x] Particles: see $\epsilon$ def'n (YJ07)
    - [ ] slope is $s$ (growth rate): pick two points to measure
    - [ ] make sure my $s$ is right units
    - [ ] Compare w/ Lin A in YJ07 (Fig. 4 @ various res.): should be one dot, but check input for #grid pts/$\lambda$
- [x]  Understand units in input file
    - [x] Understand diff. between orbital period and 1/$\Omega$
    - [x] Understand 3 main: time, length, mass, rho (e.g.)
        - [x] What's the "code units", e.g., 1 in time, or 1 in length
    - [x] ID sim. invariants
- [x] Check all 8 components, e.g., velocities
    - [x] Understand the 8 different components of the system
    - [x] Code solves paper's eqs. w/o units
- [x] Understand input file
    - [x] Cross reference w/ pgen `streaming_instability.cpp`
